server:
  port: 8089

spring:
  datasource:
    #driver-class-name: org.postgresql.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:postgresql://localhost:5432/postgres?currentSchema=test
    username: postgres
    password: postgres
    tomcat:
      initialSize: 1
      minIdle: 1
      maxIdle: 1
      maxActive: 10
      validationQuery: SELECT 1
      validationQueryTimeout: 20
      validationInterval: 60000
      testWhileIdle: true
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

kafka:
  servers:  localhost\:9092
#  topicName:  test
  topicName:  word_count
  autoCommit: false
  maxPollRecords: 100
  groupId: groupA
  commitRule: earliest

logging.config: classpath:logback/logback.xml
